/**
 * Regenerates `packages/cards/src/scripts/_generated.ts`, the static barrel `src/index.ts` folds
 * into `CARDS` (BUILD M4-T2).
 *
 * Why a generated file: `packages/cards/src/**` is pure — no fs, no dynamic `import()`
 * (CLAUDE.md rule 4, enforced by eslint's `no-restricted-imports`/`no-restricted-globals` on
 * `PURE_SOURCES`) — so the registry cannot read `src/scripts/` at runtime. A tool writes the
 * imports instead, and the 109 card files are discovered here, once, at build/test time.
 *
 * Run it after adding, renaming or deleting a card script file:
 *
 *   pnpm exec tsx packages/cards/scripts/gen-registry.ts    # from the repo root
 *   tsx scripts/gen-registry.ts                             # from packages/cards
 *   pnpm --filter @jackioh/cards gen
 *
 * Every path resolves from this file's own URL, never `process.cwd()`, so both spellings work, and
 * `test/globalSetup.ts` imports `generateBarrel()` instead of shelling out.
 *
 * Exit code: 0 when the barrel is up to date or was rewritten, 1 only on a real failure (an
 * unreadable catalog or an unwritable file). A filename that names no catalog card is a warning on
 * stderr, not a failure: with 30 agents adding files, refusing to regenerate would block everyone.
 */

import { mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { compareSortKeys, moduleAliasOf, resolveBasename, sortKey } from "./naming";

/** Package-relative labels, so the output reads the same from either working directory. */
const SCRIPTS_DIR_LABEL = "src/scripts";
const GENERATED_LABEL = `${SCRIPTS_DIR_LABEL}/_generated.ts`;

const SCRIPTS_DIR = fileURLToPath(new URL("../src/scripts/", import.meta.url));
const GENERATED_PATH = fileURLToPath(new URL("../src/scripts/_generated.ts", import.meta.url));
const CATALOG_PATH = fileURLToPath(new URL("../catalog.json", import.meta.url));

export type ScriptFile = {
  /** Filename without the `.ts` extension, e.g. `051-1-kys-empty-notebook`. */
  basename: string;
  /** The catalog id the filename names, or `undefined` when it names no shipped card. */
  id: string | undefined;
};

export type GenerateResult = {
  path: string;
  files: readonly ScriptFile[];
  /** False when the file on disk already held exactly this content. */
  changed: boolean;
  /** Basenames that match no catalog id — reported, still imported. */
  unknown: readonly string[];
};

/** Every catalog id, read with fs: a script must not import `catalog.json` through the package. */
function catalogIds(): readonly string[] {
  const raw: unknown = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new Error(`${CATALOG_PATH}: expected a JSON object keyed by card id`);
  }
  return Object.keys(raw);
}

/**
 * The card script files in `src/scripts/`: every `*.ts` whose basename does not start with `_`
 * (`_generated.ts` itself, and any future private helper), test files excluded.
 */
function scriptFiles(ids: readonly string[]): ScriptFile[] {
  let entries: string[];
  try {
    entries = readdirSync(SCRIPTS_DIR);
  } catch {
    // First run: the directory arrives with the first card file (BUILD M4-T4).
    mkdirSync(SCRIPTS_DIR, { recursive: true });
    entries = [];
  }

  const files = entries
    .filter((name) => name.endsWith(".ts") && !name.endsWith(".d.ts") && !name.endsWith(".test.ts"))
    .filter((name) => !name.startsWith("_"))
    .map((name) => {
      const basename = name.slice(0, -".ts".length);
      return { basename, id: resolveBasename(basename, ids) };
    });

  // Deterministic: §5 index ascending, card-defined tokens after their card, shared tokens last,
  // unrecognised filenames after those — never the order readdir happened to return.
  return files.sort((a, b) => compareSortKeys(sortKey(a.basename, a.id), sortKey(b.basename, b.id)));
}

/** The whole text of `_generated.ts`, both for the empty case and for 109 files. */
export function renderBarrel(files: readonly ScriptFile[]): string {
  const lines: string[] = [
    "// GENERATED by packages/cards/scripts/gen-registry.ts — DO NOT EDIT THIS FILE BY HAND.",
    "//",
    "// One `import * as` per card script file in `src/scripts/`, in SPEC §5 index order, and the",
    "// array `src/index.ts` folds into `CARDS` (BUILD M4-T2). `src/**` is pure, so the registry",
    "// cannot read the directory itself (CLAUDE.md rule 4); this file is that directory read,",
    "// frozen into static imports.",
    "//",
    "// Regenerate after adding, renaming or deleting a card script:",
    "//   pnpm exec tsx packages/cards/scripts/gen-registry.ts",
    "//",
    "// `CardModule` is a type-only import, so it is erased at runtime (verbatimModuleSyntax): the",
    "// index.ts -> _generated.ts -> index.ts cycle exists for the type checker only.",
    "",
    'import type { CardModule } from "../index";',
    "",
  ];

  if (files.length === 0) {
    lines.push(
      "// No card script files exist yet — BUILD M4-T4 lands the 109 of them. This is the valid",
      "// empty case: the package compiles and `CARDS` is `{}`.",
      "export const SCRIPT_MODULES: readonly CardModule[] = [];",
      "",
    );
    return lines.join("\n");
  }

  for (const file of files) {
    lines.push(`import * as ${moduleAliasOf(file.basename)} from "./${file.basename}";`);
  }
  lines.push("", "export const SCRIPT_MODULES: readonly CardModule[] = [");
  for (const file of files) {
    lines.push(`  ${moduleAliasOf(file.basename)},`);
  }
  lines.push("];", "");
  return lines.join("\n");
}

/**
 * Writes the barrel when its content differs. The write goes to a temp path in the same directory
 * and is then renamed, which is atomic on one filesystem: a concurrent `tsc`, vitest or another
 * agent's run reads either the old file or the new one, never a half-written one.
 */
export function generateBarrel(): GenerateResult {
  const ids = catalogIds();
  const files = scriptFiles(ids);
  const next = renderBarrel(files);

  let current: string | undefined;
  try {
    current = readFileSync(GENERATED_PATH, "utf8");
  } catch {
    current = undefined;
  }

  if (current !== next) {
    // `process.pid` (not Date.now/Math.random, which eslint bans across packages/cards) keeps two
    // concurrent runs on separate temp files.
    const temp = `${GENERATED_PATH}.${process.pid}.tmp`;
    writeFileSync(temp, next, "utf8");
    renameSync(temp, GENERATED_PATH);
  }

  return {
    path: GENERATED_PATH,
    files,
    changed: current !== next,
    unknown: files.filter((file) => file.id === undefined).map((file) => file.basename),
  };
}

function main(): void {
  let result: GenerateResult;
  try {
    result = generateBarrel();
  } catch (error) {
    console.error(`gen-registry: FAILED to write ${GENERATED_LABEL}`);
    console.error(`  ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }

  for (const basename of result.unknown) {
    console.error(
      `gen-registry: WARNING ${SCRIPTS_DIR_LABEL}/${basename}.ts names no catalog card — check the`,
      `filename convention (NNN-slug, NNN-N-slug, t-slug; see scripts/naming.ts). It is still`,
      `imported, and src/index.ts will throw if its \`def.id\` is not in the catalog.`,
    );
  }

  const count = result.files.length;
  const cards = `${count} script file${count === 1 ? "" : "s"}`;
  console.log(`gen-registry: ${result.changed ? "wrote" : "unchanged"} ${GENERATED_LABEL} (${cards})`);
}

// Run as a CLI; stay silent when imported (e.g. by `test/globalSetup.ts`, which calls
// `generateBarrel()` itself).
const entry = process.argv[1];
if (entry !== undefined && pathToFileURL(entry).href === import.meta.url) main();
