// #93.1 Combo-Fodder (SPEC §8.4, §7, R81, R85, R50, R275, R276). Generated by radiant #93
// Combo-Index.
//
// Base: "Deal 2 damage to a target, Lifesteal". Radiant: "Deal 4 damage to a target, Lifesteal"
// (§8's cell "4 damage"; R276 gave the token a Radiant face, R275 doubles its number). The damage is
// the only difference: the target, the Lifesteal and everything below hold on both faces.
//
// §7's spell-token paragraph: "Spell tokens (Notebook, CN-Virus, Combo-Fodder) live in hand and
// library like real cards and go to the graveyard after resolving; they are still excluded from
// random pools and from Discover unless named". Both halves are data, not script: the def's
// `token: true` with `type: "Spell"` keeps it out of `catalog.query`'s pools (§5.1) while
// `isUnitToken` (`engine/src/zones.ts`) is false for it, so `moveToZone` sends it to the graveyard
// after §10.5 step 7 instead of making it cease to exist (R11). R50 then lets #72 Reminisce
// Discover it back out of that graveyard, because Reminisce discovers from the actual pile.
//
// "A target" is §8's unnarrowed target — "the player picks at play time from all legal units and
// heroes on either side" — so it is a DECLARED play-time choice travelling in the `play` action and
// never a prompt (R81, §10.6). An empty target set fizzles the damage and the spell still counts as
// played (§8 Conventions), which is what `resolveTarget` returning null already does.
//
// Lifesteal: §4.4 step 8 reads Lifesteal off the source's keywords, and this token prints it on
// both faces, so that route alone would heal. The `lifesteal` flag is passed anyway because §8
// states the Lifesteal as part of the EFFECT, which is R85's case ("an effect whose own text says
// its damage has Lifesteal heals its controller's hero all the same, without granting the source the
// keyword"). `dealDamage` ORs the two sources, so stating it twice heals once, and the heal is the
// amount actually dealt — Armor, the Anti-oneshot cap and R63's zero rule all apply to it.

import type { Script } from "@jackioh/engine";
import type { TargetDecl } from "@jackioh/shared";
import { damage } from "@jackioh/engine/effects";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-093-1");

/** §8: "Deal 2 damage", radiant "Deal 4 damage". */
const BASE_DAMAGE = 2;
const RADIANT_DAMAGE = 4;

/** R81: "a target" — any unit or hero on either side, picked with the play. */
const targets: TargetDecl[] = [
  { kind: "target", min: 1, max: 1, filter: { side: "any", of: ["unit", "hero"] } },
];

function comboFodder(amount: number): Script {
  return {
    targets,
    cry: () => [damage({ to: { of: "chosen" }, amount, lifesteal: true })],
  };
}

export const base: Script = comboFodder(BASE_DAMAGE);

export const radiant: Script = comboFodder(RADIANT_DAMAGE);
