// #95.1 Chaos Golem (SPEC §8.4, §7, R11, R275, R276). Generated by #95 Call to Chaos's eighth
// effect.
//
// Base: 10/10 "Rush, Lifesteal, Divine Shield, First Strike". Radiant: 20/20 "Charge, Lifesteal,
// Divine Shield, First Strike" (R276 gave the token a Radiant face: R275 doubles its stats and, a
// keyword-only unit, trades Rush for the stronger Charge). There is no script: all four keywords
// and the stats of each face are printed on the catalog, and §10.4 layer 1 reads them off the face
// the instance's radiant flag picks, so granting any of them here would either duplicate them in the
// keyword set or re-print a stat the catalog already owns (the contract: a script never restates its
// card's data).
//
// Where each keyword's behaviour lives instead:
//   Rush          — §4.1: lifts summoning sickness for UNIT targets only, so the turn it arrives it
//                   may attack a unit but not the hero. `isSick`/`whyCannotAttack` in `combat.ts`.
//   Charge        — the radiant face's in Rush's place: no summoning sickness at all, so a Golem
//                   made Radiant the turn it arrived may attack the hero at once (§5.2: a keyword
//                   the radiant face gains applies immediately).
//   Lifesteal     — §4.4 step 8: heals its controller's hero by the amount actually dealt, after
//                   Armor and the Anti-oneshot cap, and by nothing when R63 reduced the hit to 0.
//   Divine Shield — §4.4 step 1: negates the whole first hit and is spent (`divineShieldSpent`),
//                   and R63's zero rule keeps the shield when the hit was 0 to begin with.
//   First Strike  — §4.3: it deals its damage before the defender strikes back, so a defender it
//                   kills never hits it.
//
// R11 and §7 are the rest of the card, and are likewise data: `token: true` with `type: "Unit"`
// makes `isUnitToken` true, so `moveToZone` has it cease to exist the moment it leaves the field —
// bounce, destroy, exile or transform — and it never enters a graveyard or exile, which is also why
// it can never feed #89 Corpse Eater (R11).

import type { Script } from "@jackioh/engine";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-095-1");

export const base: Script = {};

/**
 * The radiant face differs in data only — 20/20, Charge for Rush — which layer 1 reads off
 * `def.radiant`; neither face has text a script would carry, so the radiant Script is the base one.
 */
export const radiant: Script = base;
