// GENERATED by packages/cards/scripts/gen-registry.ts — DO NOT EDIT THIS FILE BY HAND.
//
// One `import * as` per card script file in `src/scripts/`, in SPEC §5 index order, and the
// array `src/index.ts` folds into `CARDS` (BUILD M4-T2). `src/**` is pure, so the registry
// cannot read the directory itself (CLAUDE.md rule 4); this file is that directory read,
// frozen into static imports.
//
// Regenerate after adding, renaming or deleting a card script:
//   pnpm exec tsx packages/cards/scripts/gen-registry.ts
//
// `CardModule` is a type-only import, so it is erased at runtime (verbatimModuleSyntax): the
// index.ts -> _generated.ts -> index.ts cycle exists for the type checker only.

import type { CardModule } from "../index";

import * as m001_big_d_fender from "./001-big-d-fender";
import * as m002_bigot from "./002-bigot";
import * as m003_right_house_defender from "./003-right-house-defender";
import * as m004_gary_the_gambler from "./004-gary-the-gambler";
import * as m005_stockpile from "./005-stockpile";
import * as m006_mana_well from "./006-mana-well";
import * as m007_jewelosco_scarab from "./007-jewelosco-scarab";
import * as m008_mr_vanilla from "./008-mr-vanilla";
import * as m009_moths_to_the_flame from "./009-moths-to-the-flame";
import * as m010_rapid_replenish from "./010-rapid-replenish";
import * as m011_tempo_timmy from "./011-tempo-timmy";
import * as m012_duplicating_felinors from "./012-duplicating-felinors";
import * as m013_jlockeed_shredder_10 from "./013-jlockeed-shredder-10";
import * as m014_jlockeeds_weapons from "./014-jlockeeds-weapons";
import * as m015_me_and_mr_token from "./015-me-and-mr-token";
import * as m016_hit_job from "./016-hit-job";
import * as m017_flood from "./017-flood";
import * as m018_bread_and_butter from "./018-bread-and-butter";
import * as m019_midrange_menace from "./019-midrange-menace";
import * as m020_pointmaster from "./020-pointmaster";
import * as m021_hinder from "./021-hinder";
import * as m022_carnivorous_cube from "./022-carnivorous-cube";
import * as m023_reoccurring_dream from "./023-reoccurring-dream";
import * as m024_efficiency_dividend from "./024-efficiency-dividend";
import * as m025_4_mana_7_7 from "./025-4-mana-7-7";
import * as m026_glowy_jelly_bean from "./026-glowy-jelly-bean";
import * as m027_blood_ridden_glowy_jelly_bean from "./027-blood-ridden-glowy-jelly-bean";
import * as m028_knockoff_temu_glowy_jelly_bean from "./028-knockoff-temu-glowy-jelly-bean";
import * as m029_giga_glowy_jelly_bean from "./029-giga-glowy-jelly-bean";
import * as m030_archivist from "./030-archivist";
import * as m031_kys_math_equation from "./031-kys-math-equation";
import * as m032_prem_panther from "./032-prem-panther";
import * as m033_unstable_clone_machine from "./033-unstable-clone-machine";
import * as m034_collateral_damage from "./034-collateral-damage";
import * as m035_lunar_eclipse from "./035-lunar-eclipse";
import * as m036_magic_jammed from "./036-magic-jammed";
import * as m037_gravedigger from "./037-gravedigger";
import * as m038_quickstriker from "./038-quickstriker";
import * as m039_recycling_initiative from "./039-recycling-initiative";
import * as m040_echoes_of_the_forgotten from "./040-echoes-of-the-forgotten";
import * as m041_sheepish from "./041-sheepish";
import * as m042_eugenics from "./042-eugenics";
import * as m043_big_felinor from "./043-big-felinor";
import * as m044_true_strike from "./044-true-strike";
import * as m045_deft_duelist from "./045-deft-duelist";
import * as m046_suppressive_aura from "./046-suppressive-aura";
import * as m047_fig_of_life from "./047-fig-of-life";
import * as m048_5pek_controller from "./048-5pek-controller";
import * as m049_snom_bunny_mind_control from "./049-snom-bunny-mind-control";
import * as m050_kpop_fanatic from "./050-kpop-fanatic";
import * as m051_kys_private_tutor from "./051-kys-private-tutor";
import * as m051_1_kys_empty_notebook from "./051-1-kys-empty-notebook";
import * as m052_silly_silas from "./052-silly-silas";
import * as m053_reno from "./053-reno";
import * as m054_straaza from "./054-straaza";
import * as m055_lava_golem from "./055-lava-golem";
import * as m056_jilliax from "./056-jilliax";
import * as m057_conjure_ky from "./057-conjure-ky";
import * as m058_rush_token_farm from "./058-rush-token-farm";
import * as m059_unbiased_immigration from "./059-unbiased-immigration";
import * as m060_bear_honeypot from "./060-bear-honeypot";
import * as m061_prejudiced_postdoc from "./061-prejudiced-postdoc";
import * as m062_friend_of_felinors from "./062-friend-of-felinors";
import * as m063_plastic_surgery from "./063-plastic-surgery";
import * as m064_gifted_program from "./064-gifted-program";
import * as m065_masochism_mask from "./065-masochism-mask";
import * as m065_1_spikey_pillow from "./065-1-spikey-pillow";
import * as m066_the_rock from "./066-the-rock";
import * as m067_zoomerbin_oomen from "./067-zoomerbin-oomen";
import * as m068_twisted_sorcerer from "./068-twisted-sorcerer";
import * as m069_call_to_arms from "./069-call-to-arms";
import * as m070_spiteful_stab from "./070-spiteful-stab";
import * as m071_intern_stimmy from "./071-intern-stimmy";
import * as m072_reminisce from "./072-reminisce";
import * as m073_anti_oneshot_armor from "./073-anti-oneshot-armor";
import * as m074_adaptive_ui from "./074-adaptive-ui";
import * as m075_infinite_reserves from "./075-infinite-reserves";
import * as m076_field_of_dreams from "./076-field-of-dreams";
import * as m077_professor_curvature from "./077-professor-curvature";
import * as m078_fullsend from "./078-fullsend";
import * as m079_twinspell from "./079-twinspell";
import * as m080_zao_gao from "./080-zao-gao";
import * as m081_radiant_saintess from "./081-radiant-saintess";
import * as m082_kys_trial from "./082-kys-trial";
import * as m083_transmogulate from "./083-transmogulate";
import * as m084_going_long from "./084-going-long";
import * as m085_unlicensed_experimentation from "./085-unlicensed-experimentation";
import * as m086_miss_mrow from "./086-miss-mrow";
import * as m087_pocket_chaos from "./087-pocket-chaos";
import * as m088_twisting_nether from "./088-twisting-nether";
import * as m089_corpse_eater from "./089-corpse-eater";
import * as m090_cn_viral_injection from "./090-cn-viral-injection";
import * as m090_1_cn_virus from "./090-1-cn-virus";
import * as m091_fed_fauci from "./091-fed-fauci";
import * as m092_felinor_fiender from "./092-felinor-fiender";
import * as m093_combo_index from "./093-combo-index";
import * as m093_1_combo_fodder from "./093-1-combo-fodder";
import * as m094_genns_greed from "./094-genns-greed";
import * as m095_call_to_chaos from "./095-call-to-chaos";
import * as m095_1_chaos_golem from "./095-1-chaos-golem";
import * as m096_my_pawn from "./096-my-pawn";
import * as m097_zephyrs from "./097-zephyrs";
import * as m098_heroic_power from "./098-heroic-power";
import * as m099_craft_a_card from "./099-craft-a-card";
import * as m100_ceaseless_void from "./100-ceaseless-void";
import * as mt_bread from "./t-bread";
import * as mt_coin from "./t-coin";
import * as mt_felinor from "./t-felinor";
import * as mt_rush from "./t-rush";
import * as mt_sheep from "./t-sheep";

export const SCRIPT_MODULES: readonly CardModule[] = [
  m001_big_d_fender,
  m002_bigot,
  m003_right_house_defender,
  m004_gary_the_gambler,
  m005_stockpile,
  m006_mana_well,
  m007_jewelosco_scarab,
  m008_mr_vanilla,
  m009_moths_to_the_flame,
  m010_rapid_replenish,
  m011_tempo_timmy,
  m012_duplicating_felinors,
  m013_jlockeed_shredder_10,
  m014_jlockeeds_weapons,
  m015_me_and_mr_token,
  m016_hit_job,
  m017_flood,
  m018_bread_and_butter,
  m019_midrange_menace,
  m020_pointmaster,
  m021_hinder,
  m022_carnivorous_cube,
  m023_reoccurring_dream,
  m024_efficiency_dividend,
  m025_4_mana_7_7,
  m026_glowy_jelly_bean,
  m027_blood_ridden_glowy_jelly_bean,
  m028_knockoff_temu_glowy_jelly_bean,
  m029_giga_glowy_jelly_bean,
  m030_archivist,
  m031_kys_math_equation,
  m032_prem_panther,
  m033_unstable_clone_machine,
  m034_collateral_damage,
  m035_lunar_eclipse,
  m036_magic_jammed,
  m037_gravedigger,
  m038_quickstriker,
  m039_recycling_initiative,
  m040_echoes_of_the_forgotten,
  m041_sheepish,
  m042_eugenics,
  m043_big_felinor,
  m044_true_strike,
  m045_deft_duelist,
  m046_suppressive_aura,
  m047_fig_of_life,
  m048_5pek_controller,
  m049_snom_bunny_mind_control,
  m050_kpop_fanatic,
  m051_kys_private_tutor,
  m051_1_kys_empty_notebook,
  m052_silly_silas,
  m053_reno,
  m054_straaza,
  m055_lava_golem,
  m056_jilliax,
  m057_conjure_ky,
  m058_rush_token_farm,
  m059_unbiased_immigration,
  m060_bear_honeypot,
  m061_prejudiced_postdoc,
  m062_friend_of_felinors,
  m063_plastic_surgery,
  m064_gifted_program,
  m065_masochism_mask,
  m065_1_spikey_pillow,
  m066_the_rock,
  m067_zoomerbin_oomen,
  m068_twisted_sorcerer,
  m069_call_to_arms,
  m070_spiteful_stab,
  m071_intern_stimmy,
  m072_reminisce,
  m073_anti_oneshot_armor,
  m074_adaptive_ui,
  m075_infinite_reserves,
  m076_field_of_dreams,
  m077_professor_curvature,
  m078_fullsend,
  m079_twinspell,
  m080_zao_gao,
  m081_radiant_saintess,
  m082_kys_trial,
  m083_transmogulate,
  m084_going_long,
  m085_unlicensed_experimentation,
  m086_miss_mrow,
  m087_pocket_chaos,
  m088_twisting_nether,
  m089_corpse_eater,
  m090_cn_viral_injection,
  m090_1_cn_virus,
  m091_fed_fauci,
  m092_felinor_fiender,
  m093_combo_index,
  m093_1_combo_fodder,
  m094_genns_greed,
  m095_call_to_chaos,
  m095_1_chaos_golem,
  m096_my_pawn,
  m097_zephyrs,
  m098_heroic_power,
  m099_craft_a_card,
  m100_ceaseless_void,
  mt_bread,
  mt_coin,
  mt_felinor,
  mt_rush,
  mt_sheep,
];
