// T-bread Bread Token (SPEC §7, R37): cost 0, Unit/Token, printed 0/0, no text, radiant form "none".
// Generated by #18 Bread and Butter only.
//
// R37 is the whole card: the source names no token ("a X/X Token"), so the spec names it Bread
// Token, gives it cost 0 and no keywords, and says "it counts as a Token for every filter" — which
// `catalog.json`'s `token: true` plus the `Token` tag already do (§5.1, `asksForTokens` in
// engine/src/catalog.ts). There is nothing for a script to add.
//
// PRINTED 0/0 AND THE X/X IT IS ALWAYS SUMMONED AS (§7 "Stat overrides", R37, R52).
// §7: "Printed 0/0; always summoned as X/X through `statsOverride`". The override is instance data
// (§10.1) written by the `summon` verb, and §10.4 layer 1 reads it AHEAD of the printed face —
// `faceOf` (engine/src/layers.ts) is `instance.statsOverride?.attack ?? face.attack`, so a Bread
// Token summoned as 3/3 is a 3/3 everywhere, with the printed 0/0 only ever showing through the def.
// A Bread Token that somehow reaches the field with no override is its printed 0/0 and dies at the
// next state check (§4.5) — and being a unit token it ceases to exist rather than reaching a
// graveyard (R11).
//
// The X itself belongs to #18, not here: "X = that player's unspent mana" at the end-of-turn trap
// window (R62), radiant 3X, and R52 gives the token to the TRAP'S controller whichever player ended
// the turn with mana left. A reviewer should look for all of that in `src/scripts/018-…`, which
// calls `summon({ defId: "core-t-bread", statsOverride: { attack: x, health: x } })`.
// R57 keeps that `statsOverride` on a copy, and R78 clears it when the token leaves the field —
// both engine-side, neither this card's.
//
// Radiant form: §7 says "none", so `def.radiant` equals `def.base` (BUILD M4-T1) and the radiant
// Script is the base Script itself (R74 still sets the instance flag; the flag changes nothing).

import type { Script } from "@jackioh/engine";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-t-bread");

export const base: Script = {};

/** §7 "Radiant form: none" — the radiant face is the base face (BUILD M4-T1, R74). */
export const radiant: Script = base;
