// T-felinor Felinor Token (SPEC §7, R275): cost 1, Unit/Felinor/Token, 1/1, no text, radiant form
// 2/2 with Rush.
// Generated by #62 Friend of Felinors and #98 Heroic Power.
//
// There is no script, and the one thing worth saying about this token is why the Felinor tag needs
// none: it is catalog data (`tags: ["Felinor", "Token"]`), and every card that cares reads the def's
// tags through the engine rather than asking the token anything:
//   #43 Big Felinor      — `destroyAll({ notTags: ["Felinor"] })`, so a Felinor Token survives its
//                          Cry on either face (`src/scripts/043-big-felinor.ts`).
//   #92 Felinor Fiender  — `setStat` (§10.4 layer 2, R39) sums "all your Felinors, including ones
//                          under a Stack" (R13), and this token is one of them.
//   #62 / #98            — name this def when they summon it; the summon verb is theirs.
// The Token tag is the §5.1 pool rule (`asksForTokens` in engine/src/catalog.ts): a Felinor pool
// never offers this token unless it also asks for tokens.
//
// 1/1 is printed on the catalog face (§10.4 layer 1, `faceOf`), and R11's vanishing is
// `isUnitToken`/`moveToZone` in engine/src/zones.ts — see `src/scripts/t-rush.ts` for that list.
//
// Radiant form: §7 prints 2/2 with Rush (issue #1; R275 added Rush), which is catalog data on
// `def.radiant` that layer 1 reads off the radiant face, so the radiant Script is the base Script
// itself: neither face has text a script would carry, and Rush is §4.1's, enforced by `combat.ts`.

import type { Script } from "@jackioh/engine";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-t-felinor");

export const base: Script = {};

/** §7's radiant 2/2 with Rush is printed on the catalog face; there is no text for a script to carry. */
export const radiant: Script = base;
