// T-rush Rush Token (SPEC §7): cost 1, Unit/Token, 3/3, "Rush", radiant form 6/6, Rush.
// Generated by #15, #58, #60, #74 (X/X), #75, #80, #95 (Radiant), #98.
//
// There is no script. Everything the §7 row states is either catalog data or an engine rule, and a
// card file that restated any of it would double it:
//
//   3/3 and Rush  — printed on the catalog face. §10.4 layer 1 reads them off the def (`faceOf` in
//                   engine/src/layers.ts) for both faces, so `grantKeyword({ kind: "Rush" })` here
//                   would add a second, redundant source of the same keyword. Rush itself is §4.1's
//                   and §4.2's: it lifts summoning sickness for unit targets only, which
//                   `combat.ts` enforces (`isSick`, `whyCannotAttack`).
//   Token         — `token: true` plus the `Token` tag in `catalog.json`, which is what keeps it out
//                   of every random pool and Discover unless the pool names tokens (§5.1,
//                   `asksForTokens` in engine/src/catalog.ts).
//   Vanishing     — R11 and §3.2: a unit token ceases to exist when it leaves the field and never
//                   enters a graveyard or exile, and a unit-token CARD in a hand or library (#75
//                   Infinite Reserves, or a copy per R34/R57) ceases to exist if it leaves that zone
//                   other than by being drawn or played, burning included. That is `isUnitToken` and
//                   `moveToZone` in engine/src/zones.ts, one rule for every token, so no card file
//                   owns it. `test/t-rush.test.ts` asserts it rather than implementing it.
//
// Radiant form: §7 prints 6/6, Rush (issue #1), which is catalog data on `def.radiant` that layer 1
// reads off the radiant face, so the radiant Script is the base Script itself: neither face has text
// a script would carry.
//
// WHERE THE §7 "STAT OVERRIDES" BULLET LIVES — NOT HERE. A reviewer should not look for any of
// these in this file:
//   #74 Adaptive UI  — summons this token as X/X (radiant 3X/3X) with `statsOverride` on its own
//                      `summon` call (`src/scripts/074-adaptive-ui.ts`).
//   #95 Call to Chaos — not one of these any more: it summons five on the token's own Radiant
//                      face (6/6, §7), a plain `summon` with `radiant: true`.
//   #58 Rush Token Farm radiant — "+3/+3 to all your Rush Tokens" is an `aura` (§10.4 layer 5) on
//                      the FIELD SPELL, keyed on this def, so it belongs to `058-…`'s AuraHook.
//   #75 Infinite Reserves — `staticFlags.infiniteReserves` on #75 puts a Rush Token CARD in hand
//                      instead of taking fatigue; the card that sits in the hand is this def.
// A `statsOverride` is instance data (§10.1) that `faceOf` reads ahead of the printed 3/3, so this
// token needs nothing for any of them.

import type { Script } from "@jackioh/engine";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-t-rush");

export const base: Script = {};

/** §7's radiant 6/6 is printed on the catalog face; there is no text for a script to carry. */
export const radiant: Script = base;
