// T-sheep Sheep Token (SPEC §7): cost 1, Unit/Token, 1/1, "worth 2 Tributes", radiant form "none".
// Generated by #41 Sheepish, its only generator.
//
// There is no script. The 1/1 is printed on the catalog face (§10.4 layer 1, `faceOf`), the Token
// tag keeps it out of every random pool (§5.1, `asksForTokens`), and R11's vanishing is
// `isUnitToken`/`moveToZone` in engine/src/zones.ts — see `src/scripts/t-rush.ts` for that list.
//
// "WORTH 2 TRIBUTES" IS A PLAY-VALIDATOR RULE, NOT A SCRIPT (§3.2, §6.3, R81).
//   §3.2: "Sheep Tokens are worth 2 Tributes while on the field."
//   §6.3 Tribute X: "the Sheep Token counts as 2 toward that X while it is on the field (§3.2) …
//   A tribute written into a card's script is an ordinary Sacrifice of the permanent that script
//   names, where the Sheep Token's 2 never applies."
// So the 2 is worth exactly two things, both outside this file:
//   * the additional COST of playing a Tribute X card (#55 Lava Golem, #66 The Rock), which the play
//     validator charges — `tributeValueOf` in engine/src/playChoices.ts returns 2 for the def whose
//     §5 index is `SHEEP_TOKEN_INDEX` ("T-sheep") and 1 for every other unit, and
//     `legalTributeSets`/`refuseTributes` build and check the payment with it; and
//   * nothing at all for a script tribute: #22 Carnivorous Cube's Cry is a plain `sacrifice` of the
//     one permanent the play named (R41), so a Sheep eaten there pays for one permanent, not two.
//
// `StaticFlags` (engine/src/script.ts) has `tribute?: number`, which is what a card COSTS to play,
// not what a card is WORTH, so there is no flag to set here and nothing is blocked: the rule is
// implemented, keyed on the §5 index. `StaticFlags.tributeWorth?: number`, read by
// `tributeValueOf` and defaulting to 1, would move the rule from an index string in the engine into
// this card file, which is where CLAUDE.md rule 6 would rather have it — reported, not needed.
// `test/t-sheep.test.ts` asserts the worth through the engine's own `tributeValueOf`.
//
// Radiant form: §7 says "none", so `def.radiant` equals `def.base` (BUILD M4-T1) and the radiant
// Script is the base Script itself.

import type { Script } from "@jackioh/engine";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-t-sheep");

export const base: Script = {};

/** §7 "Radiant form: none" — the radiant face is the base face (BUILD M4-T1, R74). */
export const radiant: Script = base;
