// T-sheep Sheep Token (SPEC §7): cost 1, Unit/Token, 1/1, "worth 2 Tributes"; radiant 2/2, "worth
// 3 Tributes". Generated by #41 Sheepish, its only generator.
//
// The script is one static flag. The 1/1 is printed on the catalog face (§10.4 layer 1, `faceOf`),
// the Token tag keeps it out of every random pool (§5.1, `asksForTokens`), and R11's vanishing is
// `isUnitToken`/`moveToZone` in engine/src/zones.ts — see `src/scripts/t-rush.ts` for that list.
//
// "WORTH 2 TRIBUTES" (§3.2, §6.3, §7).
//   §3.2: "Sheep Tokens are worth 2 Tributes while on the field", and §7's radiant face is worth 3.
//   §6.3 Tribute X: "the Sheep Token counts as 2 toward that X while it is on the field (§3.2) …
//   A tribute written into a card's script is an ordinary Sacrifice of the permanent that script
//   names, where the Sheep Token's 2 never applies."
// The worth is the face's text, so it is this file's static flag, `tributeWorth`, and the play
// validator reads it through `tributeValueOf` (engine/src/playChoices.ts): the Tribute X cost of
// #55 Lava Golem and #66 The Rock, which `legalTributeSets`/`refuseTributes` build and check with it.
// A script tribute (#22 Carnivorous Cube's Cry) is a plain `sacrifice` and never reads it (R41). As a
// flag of the face, it goes with the face: a Vanilla Sheep has no text and is worth 1 (R115), the
// radiant face's 3 is read off a Radiant Sheep, and a Sheep #85 fused a unit onto keeps its worth,
// since a fused card's flags take the larger of its ingredients' (R102). The numbers are the
// engine's named constants (CLAUDE.md rule 9). `test/t-sheep.test.ts` asserts the worth through the
// engine's own `tributeValueOf`.
//
// Radiant form: §7 prints "2/2, worth 3 Tributes", so the radiant Script carries the 3.

import { RADIANT_SHEEP_TRIBUTE_VALUE, SHEEP_TRIBUTE_VALUE, type Script } from "@jackioh/engine";
import { cardDef } from "../catalog-data";

export const def = cardDef("core-t-sheep");

/** §3.2: "worth 2 Tributes while on the field". */
export const base: Script = { staticFlags: { tributeWorth: SHEEP_TRIBUTE_VALUE } };

/** §7's radiant face: "2/2, worth 3 Tributes". */
export const radiant: Script = { staticFlags: { tributeWorth: RADIANT_SHEEP_TRIBUTE_VALUE } };
